repos:
  - repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
      - id: black
        language_version: python3.9.1
        args: [ "--line-length=120" ]
  - repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        language_version: python3.9.1
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        language_version: python3.9.1
        entry: bash -c 'mypy "$@" || true' --
        args: [ "--no-strict-optional", "--ignore-missing-imports" ]
